name: ğŸ‘®ğŸ½â€â™€ï¸ Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout
        uses: actions/checkout@v4.1.0
      - name: âš™ï¸ Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: "11"

  test:
    needs: setup
    runs-on: macOS-latest
    steps:
      - name: âš™ï¸ Grant permissions for gradlew
        run: chmod +x gradlew
        working-directory: ~/guide-stocks-mobile-app/mobile-android-app
      - name: ğŸ“¦ Archive cache 
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: ğŸ§ª Tests
        run: ./gradlew test
        working-directory: ~/guide-stocks-mobile-app/mobile-android-app

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Grant permissions for gradlew
        run: chmod +x gradlew
        working-directory: ~/guide-stocks-mobile-app/mobile-android-app
      - name: â˜„ï¸ Android Build
        run: ./gradlew build
        working-directory:  ~/guide-stocks-mobile-app/mobile-android-app
      - name: ğŸ“¦ Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ~/guide-stocks-mobile-app/mobile-app/build/libs/