name: ğŸ‘®ğŸ½â€â™€ï¸ Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout
        uses: actions/checkout@v2
  java:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

  gradle:
    needs: [checkout, java]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

  test:
    needs: [checkout, java, gradle]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§ª Tests
        run: cd guide-stocks-mobile-app/mobile-android-app && ./gradlew test

  build:
    needs: [checkout, java, gradle, test]
    runs-on: ubuntu-latest
    steps:
      - name: â˜„ï¸ Android Build
        run: ./gradlew build
      - name: ğŸ“¦ Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/guide-stocks-mobile-app/mobile-app/build/libs/
