name: ğŸ‘®ğŸ½â€â™€ï¸ Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout
        uses: actions/checkout@v4.1.0
      - name: âš™ï¸ Java
        uses: actions/setup-java@v1
        with:
            java-version: 17

  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

  test:
      needs: [setup, gradle]
      runs-on: ubuntu-latest
      steps:
        - name: ğŸ§ª Tests
          run: cd guide-stocks-mobile-app/mobile-android-app && ./gradlew test

  build:
    needs: [setup, gradle, test]
    runs-on: ubuntu-latest
    steps:
      - name: â˜„ï¸ Android Build
        run: cd guide-stocks-mobile-app/mobile-android-app && ./gradlew build
      - name: ğŸ“¦ Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/guide-stocks-mobile-app/mobile-app/build/libs/
