name: ğŸ‘®ğŸ½â€â™€ï¸ Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout
        uses: actions/checkout@v4.1.0
      - name: âš™ï¸ Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: "11"

  test:
      needs: setup
      runs-on: macOS-latest
      steps:
        - name: ğŸ“¦ Archive cache
          uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
            restore-keys: |
              ${{ runner.os }}-gradle
        - name: ğŸ—‚ï¸ Change working directory
          run: cd ${{ runner.os }}/mobile-android-app
        - name: ğŸ§ª Tests
          run: gradle test

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‚ï¸ Change working directory
        run: cd mobile-android-app
      - name: â˜„ï¸ Android Build
        run: gradle build
      - name: ğŸ“¦ Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/guide-stocks-mobile-app/mobile-app/build/libs/
